// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('PET6-3 Contraseñas Diferentes', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('PET6-3 Contraseñas Diferentes', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1920, height: 1080 })
    {
      const element = await driver.findElement(By.css("a img"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.linkText("Registrate"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.linkText("Registrate")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("register_correo")).click()
    await driver.findElement(By.id("register_correo")).sendKeys("prueba@gmail.com")
    await driver.findElement(By.id("register_pwd")).click()
    await driver.findElement(By.id("register_pwd")).sendKeys("abcdef")
    await driver.findElement(By.id("register_confirm")).click()
    await driver.findElement(By.id("register_confirm")).sendKeys("123456")
    await driver.findElement(By.id("register_nombre")).click()
    await driver.findElement(By.id("register_nombre")).sendKeys("prueba")
    await driver.findElement(By.id("register_telefono")).click()
    await driver.findElement(By.id("register_telefono")).sendKeys("3158125800")
    await driver.findElement(By.id("register_ciudad")).click()
    await driver.findElement(By.id("register_ciudad")).sendKeys("Medellín")
    await driver.findElement(By.css(".ant-col-xs-24 .ant-btn")).click()
  })
})
