// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('PET8-2 Correo No Válido', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('PET8-2 Correo No Válido', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1920, height: 1080 })
    {
      const element = await driver.findElement(By.css("a img"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.linkText("Iniciar Sesión")).click()
    await driver.findElement(By.css(".one .input")).click()
    await driver.findElement(By.css(".one .input")).sendKeys("pepe")
    await driver.findElement(By.css(".pass .input")).click()
    await driver.findElement(By.css(".pass .input")).click()
    await driver.findElement(By.css(".pass .input")).sendKeys("123456")
    await driver.findElement(By.css(".btn")).click()
  })
})
