// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('3.1 Color Con Numeros', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('3.1 Color Con Numeros', async function() {
    // Test name: 3.1 Color Con Numeros
    // Step # | name | target | value
    // 1 | open | /pet/register | 
    await driver.get("http://localhost:3000/pet/register")
    // 2 | setWindowSize | 1294x741 | 
    await driver.manage().window().setRect({ width: 1294, height: 741 })
    // 3 | click | id=register_nombre | 
    await driver.findElement(By.id("register_nombre")).click()
    // 4 | type | id=register_nombre | prueba
    await driver.findElement(By.id("register_nombre")).sendKeys("prueba")
    // 5 | click | id=register_nombre | 
    await driver.findElement(By.id("register_nombre")).click()
    // 6 | click | id=register_nombre | 
    await driver.findElement(By.id("register_nombre")).click()
    // 7 | doubleClick | id=register_nombre | 
    {
      const element = await driver.findElement(By.id("register_nombre"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 8 | type | id=register_nombre | Mona
    await driver.findElement(By.id("register_nombre")).sendKeys("Mona")
    // 9 | click | id=register_ciudad | 
    await driver.findElement(By.id("register_ciudad")).click()
    // 10 | type | id=register_ciudad | Envigado
    await driver.findElement(By.id("register_ciudad")).sendKeys("Envigado")
    // 11 | click | id=register_raza | 
    await driver.findElement(By.id("register_raza")).click()
    // 12 | type | id=register_raza | Angus
    await driver.findElement(By.id("register_raza")).sendKeys("Angus")
    // 13 | click | id=register_color | 
    await driver.findElement(By.id("register_color")).click()
    // 14 | type | id=register_color | Blanca#4446
    await driver.findElement(By.id("register_color")).sendKeys("Blanca#4446")
    // 15 | click | id=register_edad | 
    await driver.findElement(By.id("register_edad")).click()
    // 16 | type | id=register_edad | 5
    await driver.findElement(By.id("register_edad")).sendKeys("5")
    // 17 | click | id=register_size | 
    await driver.findElement(By.id("register_size")).click()
    // 18 | click | css=#mediano > .ant-select-item-option-content | 
    await driver.findElement(By.css("#mediano > .ant-select-item-option-content")).click()
    // 19 | click | id=register_tipo | 
    await driver.findElement(By.id("register_tipo")).click()
    // 20 | runScript | window.scrollTo(0,308) | 
    await driver.executeScript("window.scrollTo(0,308)")
    // 21 | click | css=#Vaca > .ant-select-item-option-content | 
    await driver.findElement(By.css("#Vaca > .ant-select-item-option-content")).click()
    // 22 | click | css=.ant-upload > div | 
    await driver.findElement(By.css(".ant-upload > div")).click()
    // 23 | click | css=.ant-col-xs-24 .ant-btn > span | 
    await driver.findElement(By.css(".ant-col-xs-24 .ant-btn > span")).click()
  })
})
