// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('1.4 no nombre', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('1.4 no nombre', async function() {
    // Test name: 1.4 no nombre
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1294x741 | 
    await driver.manage().window().setRect({ width: 1294, height: 741 })
    // 3 | click | linkText=Registrate | 
    await driver.findElement(By.linkText("Registrate")).click()
    // 4 | click | id=register_correo | 
    await driver.findElement(By.id("register_correo")).click()
    // 5 | type | id=register_correo | juan@eia.edu.co
    await driver.findElement(By.id("register_correo")).sendKeys("juan@eia.edu.co")
    // 6 | click | id=register_pwd | 
    await driver.findElement(By.id("register_pwd")).click()
    // 7 | type | id=register_pwd | 123456
    await driver.findElement(By.id("register_pwd")).sendKeys("123456")
    // 8 | click | css=.ant-input-affix-wrapper-focused | 
    await driver.findElement(By.css(".ant-input-affix-wrapper-focused")).click()
    // 9 | type | id=register_confirm | 123456
    await driver.findElement(By.id("register_confirm")).sendKeys("123456")
    // 10 | click | id=register_telefono | 
    await driver.findElement(By.id("register_telefono")).click()
    // 11 | click | id=register_telefono | 
    await driver.findElement(By.id("register_telefono")).click()
    // 12 | type | id=register_telefono | 123456
    await driver.findElement(By.id("register_telefono")).sendKeys("123456")
    // 13 | click | id=register_ciudad | 
    await driver.findElement(By.id("register_ciudad")).click()
    // 14 | type | id=register_ciudad | Medellín
    await driver.findElement(By.id("register_ciudad")).sendKeys("Medellín")
    // 15 | click | css=.ant-col-xs-24 .ant-btn > span | 
    await driver.findElement(By.css(".ant-col-xs-24 .ant-btn > span")).click()
  })
})
