// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('2 correo invalido', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('2 correo invalido', async function() {
    // Test name: 2 correo invalido
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1294x741 | 
    await driver.manage().window().setRect({ width: 1294, height: 741 })
    // 3 | click | linkText=Registrate | 
    await driver.findElement(By.linkText("Registrate")).click()
    // 4 | click | id=register_correo | 
    await driver.findElement(By.id("register_correo")).click()
    // 5 | type | id=register_correo | juanes1gmail.com
    await driver.findElement(By.id("register_correo")).sendKeys("juanes1gmail.com")
    // 6 | click | id=register_pwd | 
    await driver.findElement(By.id("register_pwd")).click()
    // 7 | type | id=register_pwd | 123456
    await driver.findElement(By.id("register_pwd")).sendKeys("123456")
    // 8 | click | id=register_confirm | 
    await driver.findElement(By.id("register_confirm")).click()
    // 9 | type | id=register_confirm | 123456
    await driver.findElement(By.id("register_confirm")).sendKeys("123456")
    // 10 | click | id=register_nombre | 
    await driver.findElement(By.id("register_nombre")).click()
    // 11 | click | id=register | 
    await driver.findElement(By.id("register")).click()
    // 12 | click | id=register_nombre | 
    await driver.findElement(By.id("register_nombre")).click()
    // 13 | type | id=register_nombre | juan
    await driver.findElement(By.id("register_nombre")).sendKeys("juan")
    // 14 | click | id=register_telefono | 
    await driver.findElement(By.id("register_telefono")).click()
    // 15 | type | id=register_telefono | 3206795630
    await driver.findElement(By.id("register_telefono")).sendKeys("3206795630")
    // 16 | click | id=register_ciudad | 
    await driver.findElement(By.id("register_ciudad")).click()
    // 17 | type | id=register_ciudad | Medellín
    await driver.findElement(By.id("register_ciudad")).sendKeys("Medellín")
    // 18 | click | css=.ant-col-xs-24 .ant-btn > span | 
    await driver.findElement(By.css(".ant-col-xs-24 .ant-btn > span")).click()
  })
})
