// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('3.2 contraseña menos 6 char', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('3.2 contraseña menos 6 char', async function() {
    // Test name: 3.2 contraseña menos 6 char
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1294x741 | 
    await driver.manage().window().setRect({ width: 1294, height: 741 })
    // 3 | mouseOver | css=a img | 
    {
      const element = await driver.findElement(By.css("a img"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 4 | mouseOut | css=a img | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 5 | click | linkText=Registrate | 
    await driver.findElement(By.linkText("Registrate")).click()
    // 6 | click | id=register_correo | 
    await driver.findElement(By.id("register_correo")).click()
    // 7 | type | id=register_correo | prueba@gmail.com
    await driver.findElement(By.id("register_correo")).sendKeys("prueba@gmail.com")
    // 8 | click | css=.ant-input-affix-wrapper-focused | 
    await driver.findElement(By.css(".ant-input-affix-wrapper-focused")).click()
    // 9 | type | id=register_pwd | 123
    await driver.findElement(By.id("register_pwd")).sendKeys("123")
    // 10 | click | id=register_confirm | 
    await driver.findElement(By.id("register_confirm")).click()
    // 11 | type | id=register_confirm | 123
    await driver.findElement(By.id("register_confirm")).sendKeys("123")
    // 12 | click | id=register_nombre | 
    await driver.findElement(By.id("register_nombre")).click()
    // 13 | type | id=register_nombre | pruebas 6
    await driver.findElement(By.id("register_nombre")).sendKeys("pruebas 6")
    // 14 | click | id=register_telefono | 
    await driver.findElement(By.id("register_telefono")).click()
    // 15 | type | id=register_telefono | 3158125800
    await driver.findElement(By.id("register_telefono")).sendKeys("3158125800")
    // 16 | click | id=register_ciudad | 
    await driver.findElement(By.id("register_ciudad")).click()
    // 17 | type | id=register_ciudad | Medellín
    await driver.findElement(By.id("register_ciudad")).sendKeys("Medellín")
    // 18 | click | css=.ant-col-xs-24 .ant-btn > span | 
    await driver.findElement(By.css(".ant-col-xs-24 .ant-btn > span")).click()
    // 19 | mouseOver | css=.ant-col-xs-24 .ant-btn > span | 
    {
      const element = await driver.findElement(By.css(".ant-col-xs-24 .ant-btn > span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 20 | mouseOut | css=.ant-col-xs-24 .ant-btn > span | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
